Algoritmo "Antecessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Revela o número antecessor
// Autor(a)    : Juninho
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite o número que deseja saber o antecessor")
Leia (numero1)
antecessor<-numero1-(1)
escreval("O antecessor dos números é:",antecessor)

Fimalgoritmo