Algoritmo "Círculo"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Calcula a área de um circulo
// Autor(a)    : Juninho
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
raio:inteiro
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite o raio do circulo")
Leia (raio)
area<-(3.142)*(raio*raio)
escreval("O Área do circulo dos números é:",area)

Fimalgoritmo