Algoritmo "manzanopagina46exC"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Somatorio dos numeros pares de 1 ate 500
// Autor(a)    : Erik
// Data atual  : 29/03/2023
Var
// Seção de Declarações das variáveis 
contadora:inteiro
soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Enquanto contadora<501      faca
soma<- soma + contadora

contadora<- contadora +2


fimenquanto
  escreval(soma)


Fimalgoritmo