Algoritmo "Maça"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Calcula o número de ofertas
// Autor(a)    : Erik Júnior
// Data atual  : 20/03/2023
Var
// Seção de Declarações das variáveis 
 menorQueDuzia:real
 MaiorQueDuzia:real
 macas:real
 
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um valor")
   leia(macas)
   


Fimalgoritmo