Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Obama
// Descrição   : Revela o número Sucessor
// Autor(a)    : Juninho
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis 
numero1:inteiro
sucessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite o outro número que deseja saber o sucessor")
Leia (numero1)
sucessor<-numero1+1
escreval("O sucessor dos números é:",sucessor)

Fimalgoritmo